name: 'CG 3D'
description: 'Free 3D Assets'
author: 'Mohamad Rido'
email: 'mohamadrido@mail.ru'
permalink: /:title
plugin:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-category-pages
markdown: kramdown
highlighter: rouge
paginate: 15
