name: 'CG 3D'
description: 'Public Domain 3D Assets'
author: 'Pretended Studio'
email: 'pretendedstudio@mail.ru'
permalink: /:title
plugin:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
markdown: kramdown
highlighter: rouge
paginate: 15
